# Generated by Django 5.2.17 on 2026-09-11 16:07

from django.db import migrations, models

import professionals.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "social_name",
                    models.CharField(
                        max_length=150, validators=[professionals.validators.validate_nonblank]
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        max_length=100, validators=[professionals.validators.validate_nonblank]
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(
                        max_length=32, validators=[professionals.validators.validate_phone]
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        max_length=9, validators=[professionals.validators.validate_postal_code]
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        max_length=200, validators=[professionals.validators.validate_nonblank]
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=20, validators=[professionals.validators.validate_nonblank]
                    ),
                ),
                ("complement", models.CharField(blank=True, max_length=150)),
                (
                    "neighborhood",
                    models.CharField(
                        max_length=100, validators=[professionals.validators.validate_nonblank]
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=100, validators=[professionals.validators.validate_nonblank]
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AC", "AC"),
                            ("AL", "AL"),
                            ("AP", "AP"),
                            ("AM", "AM"),
                            ("BA", "BA"),
                            ("CE", "CE"),
                            ("DF", "DF"),
                            ("ES", "ES"),
                            ("GO", "GO"),
                            ("MA", "MA"),
                            ("MT", "MT"),
                            ("MS", "MS"),
                            ("MG", "MG"),
                            ("PA", "PA"),
                            ("PB", "PB"),
                            ("PR", "PR"),
                            ("PE", "PE"),
                            ("PI", "PI"),
                            ("RJ", "RJ"),
                            ("RN", "RN"),
                            ("RS", "RS"),
                            ("RO", "RO"),
                            ("RR", "RR"),
                            ("SC", "SC"),
                            ("SP", "SP"),
                            ("SE", "SE"),
                            ("TO", "TO"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["social_name", "id"],
            },
        ),
    ]
