# Generated by Django 5.2.17 on 2026-09-11 16:07

import django.db.models.deletion
from django.db import migrations, models

import appointments.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(validators=[appointments.models.validate_aware_datetime]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to="professionals.professional",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("professional", "scheduled_at"),
                        name="unique_professional_scheduled_at",
                    )
                ],
            },
        ),
    ]
